version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gidung-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gidung?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=gidung
    ports:
      - 18080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.32
    container_name: gidung-mysql
    platform: linux/amd64
    volumes:
      - db_datas:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gidung
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=gidung
      - TZ= Asia/Seoul
    ports:
      - 13306:3306

volumes:
  db_datas: